### ISSUE TITLE
Netlify form submission does not work

### ISSUE THREAD

**Issue by johnmeredith** [codebushi/gatsby-starter-forty-codebushi#1]
Hi there,
I love the template and am building something for a ocnference off the back fo it. I noticed that I cannot seem to get native Netlify forms to work. I do not get a default response message either from the native form.

**Request Header**
Host: naughty-galileo-cdca15.netlify.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://naughty-galileo-cdca15.netlify.com/
Content-Type: application/x-www-form-urlencoded
Content-Length: 75
Connection: keep-alive
Upgrade-Insecure-Requests: 1

**Response Header**
HTTP/1.0 200 Connection established
cache-control: public, max-age=0, must-revalidate
content-type: text/html; charset=utf-8
date: Thu, 13 Sep 2018 09:54:26 GMT
etag: 1536753650-ssl
age: 1
server: Netlify
x-nf-request-id: 6fa8e058-568a-46d4-a717-0efe00e00e70-28754067
X-Firefox-Spdy: h2

I am a newbie to gatsby and netlify so apologies if there is something basic missing but help would be appreciated. 

URL: [https://naughty-galileo-cdca15.netlify.com/](https://naughty-galileo-cdca15.netlify.com/)

**Comment by ChangoMan** [comment]
Hey John, I just tested the Netlify forms with this version and it worked for me. Looking at your site, it doesn't look like your `<form>` tag is correct. You'll need to make sure to include the `data-netlify="true"`. It should look like this:

```
<form name="contact" method="post" action="/success" data-netlify="true">
```
In this example, you'll also need to make a new page called `success.js` that will act like the thank-you page.

**Comment by johnmeredith** [comment]
Thanks for the feedback. I've tried several ways of including the data-netlify tag. I used your example and created a success page also, which seems to work. However the message itself does not get sent - only the success page.  

I do not get this issue with V1 and have set up an instance [here.](https://wonderful-jackson-e106c0.netlify.com/) which works perfectly.

**Comment by ChangoMan** [comment]
That's strange, the version of Gatsby should have nothing to do with how Netlify forms work. You might want to try clearing your browser's cache or visiting the V2 site in an incognito view and see if that works. Do you have the code on Github somewhere?

**Comment by ChangoMan** [comment]
You can also try and clone this repo https://github.com/codebushi/gatsby-forms which is the one I used in my demo. Try making a new site with that on Netlify and see if the forms work for you.

**Comment by johnmeredith** [comment]
My repo is here: https://github.com/johnmeredith/interop-live

**Comment by ChangoMan** [comment]
I cloned your repo and hosted it on Netlify and it was indeed not working. I then added the honeypot field and it started to work. Not sure why this is, maybe the other form was being treated as spam by Netlify? Anyways, I've created a pull request on your repo with the honeypot field, hopefully it starts working for you after that.

https://github.com/johnmeredith/interop-live/pull/1

**Comment by johnmeredith** [comment]
Thank you for your help - this is working great.  The only problem is that I redid the site in V1 ;-) Now I'll have to add the changes back into v2... 

Great job though. Much appreciated.
